#Gradle
org.gradle.java.home=/Users/giovannyvelez/Library/Java/JavaVirtualMachines/jbr-21.0.11/Contents/Home
org.gradle.jvmargs=-Xmx12g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4g"
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

#Kotlin
kotlin.code.style=official
kotlin.native.ignoreDisabledTargets=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Publishing
SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true

GROUP=com.paligot.jsonforms.kotlin
VERSION_NAME=1.0.0-SNAPSHOT

POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/GerardPaligot/jsonforms-kotlin

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/GerardPaligot/jsonforms-kotlin/
POM_SCM_CONNECTION=scm:git:git://github.com/GerardPaligot/jsonforms-kotlin.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/GerardPaligot/jsonforms-kotlin.git

POM_DEVELOPER_ID=gerardpaligot
POM_DEVELOPER_NAME=Gérard Paligot
POM_DEVELOPER_URL=https://github.com/GerardPaligot/
