[versions]
agp = "9.1.1"
androidx-activity = "1.13.0"
cupertino = "2.3.1"
jetbrains-androidx-navigation = "2.9.2"
jetbrains-androidx-viewmodel = "2.11.0"
jetbrains-compose = "1.12.0"
jetbrains-compose-material3 = "1.12.0-alpha03"
jetbrains-compose-material-icons = "1.7.3"
jetbrains-dokka = "2.2.0"
jetbrains-kotlin = "2.4.10"
jetbrains-kotlinx-binary-compatibility-validator = "0.18.1"
jetbrains-kotlinx-coroutines = "1.11.0"
jetbrains-kotlinx-serialization = "1.11.0"
jetbrains-kotlinx-collections = "0.5.1"
io-ktor = "3.5.2"
io-mockk = "1.14.11"
io-coil3 = "3.6.0"
ktlint = "14.2.0"
maven-publish = "0.37.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
cupertino = { group = "io.github.schott12521", name = "cupertino", version.ref = "cupertino" }
jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-androidx-navigation" }
jetbrains-androidx-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrains-androidx-viewmodel" }
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose" }
jetbrains-compose-components-ui-tooling-preview = { module = "org.jetbrains.compose.components:components-ui-tooling-preview", version.ref = "jetbrains-compose" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
#noinspection UnusedVersionCatalogEntry
jetbrains-compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "jetbrains-compose" }
jetbrains-compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "jetbrains-compose-material-icons" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-compose-material3" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }
#noinspection UnusedVersionCatalogEntry
jetbrains-compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "jetbrains-compose" }
#noinspection UnusedVersionCatalogEntry
jetbrains-compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "jetbrains-compose" }
jetbrains-compose-ui-test-junit4 = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "jetbrains-compose" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "jetbrains-kotlinx-collections" }
jetbrains-kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "jetbrains-kotlinx-serialization" }
io-coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "io-coil3" }
io-coil3-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "io-coil3" }
io-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "io-ktor" }
io-ktor-client-json = { group = "io.ktor", name = "ktor-client-json", version.ref = "io-ktor" }
io-ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "io-ktor" }
io-ktor-client-serialization = { group = "io.ktor", name = "ktor-client-serialization", version.ref = "io-ktor" }
io-ktor-client-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "io-ktor" }
io-ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "io-ktor" }
io-ktor-kotlinx-serialization-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "io-ktor" }
io-mockk = { group = "io.mockk", name = "mockk", version.ref = "io-mockk" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrains-kotlin" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "jetbrains-kotlinx-binary-compatibility-validator" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[bundles]
io-ktor-client = [
    "io-ktor-client-core",
    "io-ktor-client-json",
    "io-ktor-client-logging",
    "io-ktor-client-serialization",
    "io-ktor-client-negotiation",
    "io-ktor-client-cio",
    "io-ktor-kotlinx-serialization-json"
]
